[package]
name = "generic-rcsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.4"
typed-arena = "2.0.2"
itertools = "0.12.0"
binary-heap-plus = "0.5.0"
